
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTenant
metadata:
  name: test-pulsar-tenant
spec:
  name: test-tenant
  connectionRef:
    name: pulsar-connection
  adminRoles:
  - admin
  - ops
  
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: test-pulsar-namespace
spec:
  name: test-tenant/testns
  connectionRef:
    name: pulsar-connection
  backlogQuotaLimitSize: 1Gi
  backlogQuotaLimitTime: 24h
  bundles: 16
  messageTTL: 1h
  backlogQuotaRetentionPolicy: producer_request_hold
  maxProducersPerTopic: 2
  maxConsumersPerTopic: 2
  # optional
  maxConsumersPerSubscription: 2
  retentionTime: 48h
  retentionSize: 2Gi
  lifecyclePolicy: CleanUpAfterDeletion
  
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: "test-pulsar-topic123"
spec:
  name: persistent://test-tenant/testns/topic123
  connectionRef:
    name: pulsar-connection
